site_name: pydantic-settings
site_description: Pydantic Settings
strict: true
site_url: https://pydantic-docs.helpmanual.io/

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  features:
    - content.tabs.link
  logo: 'logo-white.svg'
  favicon: 'favicon.png'

repo_name: pydantic/pydantic-settings
repo_url: https://github.com/pydantic-settings/pydantic
edit_uri: edit/main/docs/
extra:
  analytics:
    provider: google
    property: UA-62733018-4

extra_css:
- 'extra/terminal.css'
- 'extra/tweaks.css'
extra_javascript:
- 'extra/redirects.js'
- 'extra/ad.js'

nav:
- Overview: index.md

markdown_extensions:
- tables
- markdown_include.include:
    base_path: docs
- toc:
    permalink: true
- admonition
- pymdownx.highlight
- pymdownx.extra
- mdx_truly_sane_lists
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true

plugins:
- search
- exclude:
    glob:
    - _build/*
    - build/*
    - examples/*
    - requirements.txt
